[extension]
name = "MouseTracker"

[[resources]]
name = "MouseTracker"
tags = ["tracker"]
entrypoint = "mouse_tracker.gd"
gui = "gui.gd"
translation-key = "MOUSE_TRACKER_TRACKER_NAME"

[[resources]]
name = "MouseTrackerLib"
tags = ["plugin"]
entrypoint = "mouse-poller"
gdnative = true
